language: node_js
node_js:
  - 12
before_install: cd packages/kodehub-backend
install:
  - npm install
script:
  - npm test
# safelist
branches:
  only:
    - release-be
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
