// flow-typed signature: ed6bf09c65a6a16ace5a85b8577b00a7
// flow-typed version: <<STUB>>/express-rate-limit_v^5.1.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-rate-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-rate-limit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-rate-limit/lib/express-rate-limit' {
  declare module.exports: any;
}

declare module 'express-rate-limit/lib/memory-store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-rate-limit/lib/express-rate-limit.js' {
  declare module.exports: $Exports<'express-rate-limit/lib/express-rate-limit'>;
}
declare module 'express-rate-limit/lib/memory-store.js' {
  declare module.exports: $Exports<'express-rate-limit/lib/memory-store'>;
}
