// flow-typed signature: aacbb2a8358ce3f6581d5cd5e9e0fb0f
// flow-typed version: <<STUB>>/graphql-scalars_v^1.0.6/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-scalars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-scalars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-scalars/index.cjs' {
  declare module.exports: any;
}

declare module 'graphql-scalars/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-scalars/index.cjs.js' {
  declare module.exports: $Exports<'graphql-scalars/index.cjs'>;
}
declare module 'graphql-scalars/index.esm.js' {
  declare module.exports: $Exports<'graphql-scalars/index.esm'>;
}
