// flow-typed signature: ce53f05f1dcc67c5529c756d0e014c64
// flow-typed version: <<STUB>>/graphql-resolvers_v^0.4.2/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-resolvers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-resolvers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-resolvers/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'graphql-resolvers/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'graphql-resolvers/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'graphql-resolvers/lib/allResolvers' {
  declare module.exports: any;
}

declare module 'graphql-resolvers/lib/combineResolvers' {
  declare module.exports: any;
}

declare module 'graphql-resolvers/lib/dependingResolvers' {
  declare module.exports: any;
}

declare module 'graphql-resolvers/lib/miscResolvers' {
  declare module.exports: any;
}

declare module 'graphql-resolvers/lib/pipeResolvers' {
  declare module.exports: any;
}

declare module 'graphql-resolvers/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-resolvers/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'graphql-resolvers/coverage/lcov-report/block-navigation'>;
}
declare module 'graphql-resolvers/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'graphql-resolvers/coverage/lcov-report/prettify'>;
}
declare module 'graphql-resolvers/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'graphql-resolvers/coverage/lcov-report/sorter'>;
}
declare module 'graphql-resolvers/index' {
  declare module.exports: $Exports<'graphql-resolvers'>;
}
declare module 'graphql-resolvers/index.js' {
  declare module.exports: $Exports<'graphql-resolvers'>;
}
declare module 'graphql-resolvers/lib/allResolvers.js' {
  declare module.exports: $Exports<'graphql-resolvers/lib/allResolvers'>;
}
declare module 'graphql-resolvers/lib/combineResolvers.js' {
  declare module.exports: $Exports<'graphql-resolvers/lib/combineResolvers'>;
}
declare module 'graphql-resolvers/lib/dependingResolvers.js' {
  declare module.exports: $Exports<'graphql-resolvers/lib/dependingResolvers'>;
}
declare module 'graphql-resolvers/lib/miscResolvers.js' {
  declare module.exports: $Exports<'graphql-resolvers/lib/miscResolvers'>;
}
declare module 'graphql-resolvers/lib/pipeResolvers.js' {
  declare module.exports: $Exports<'graphql-resolvers/lib/pipeResolvers'>;
}
declare module 'graphql-resolvers/lib/utils.js' {
  declare module.exports: $Exports<'graphql-resolvers/lib/utils'>;
}
