// flow-typed signature: b797234f6b3161ba07ed80f843c0dffe
// flow-typed version: <<STUB>>/password-validator_v^5.0.3/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'password-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'password-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'password-validator/src/constants' {
  declare module.exports: any;
}

declare module 'password-validator/src' {
  declare module.exports: any;
}

declare module 'password-validator/src/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'password-validator/src/constants.js' {
  declare module.exports: $Exports<'password-validator/src/constants'>;
}
declare module 'password-validator/src/index' {
  declare module.exports: $Exports<'password-validator/src'>;
}
declare module 'password-validator/src/index.js' {
  declare module.exports: $Exports<'password-validator/src'>;
}
declare module 'password-validator/src/lib.js' {
  declare module.exports: $Exports<'password-validator/src/lib'>;
}
